//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBmysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarm
    {
        public string AlarmDescription { get; set; }
        public Nullable<int> AlarmSource { get; set; }
        public Nullable<int> AlarmType { get; set; }
        public Nullable<int> AlarmAction { get; set; }
        public Nullable<int> AlarmWindow { get; set; }
        public Nullable<int> AlarmDevice { get; set; }
        public Nullable<double> AlarmValue { get; set; }
        public Nullable<System.DateTime> AlarmDateTime { get; set; }
        public System.DateTime AlarmImportDate { get; set; }
        public string AlarmHeader { get; set; }
        public string AlarmLog { get; set; }
        public Nullable<long> AlarmAck { get; set; }
        public int LocationID { get; set; }
        public int AlarmID { get; set; }
    
        public virtual location location { get; set; }
    }
}
