//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBmysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class app
    {
        public sbyte AppEvent { get; set; }
        public Nullable<sbyte> AppType { get; set; }
        public string AppName { get; set; }
        public Nullable<int> AppThreadID { get; set; }
        public string AppUser { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public string AppVersion { get; set; }
        public string AppInfo { get; set; }
        public int AppID { get; set; }
    }
}
