//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBmysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class connection
    {
        public string DeviceSN { get; set; }
        public sbyte ConnectionOrigin { get; set; }
        public sbyte ConnectionEvent { get; set; }
        public System.DateTime ConnectionDate { get; set; }
        public Nullable<int> ConnectionDuration { get; set; }
        public Nullable<int> ConnectionBytesReceived { get; set; }
        public Nullable<int> ConnectionBytesSent { get; set; }
        public int ConnectionIndex { get; set; }
        public string ConnectionIP { get; set; }
        public string ConnectionInfo { get; set; }
        public Nullable<int> ConnectionTotal { get; set; }
        public string ConnectionFld1 { get; set; }
        public string ConnectionFld2 { get; set; }
        public string ConnectionFld3 { get; set; }
        public string ConnectionFld4 { get; set; }
        public string ConnectionFld5 { get; set; }
        public string ConnectionFld6 { get; set; }
        public string ConnectionFld7 { get; set; }
        public string ConnectionFld8 { get; set; }
        public string ConnectionFld9 { get; set; }
        public string ConnectionFld10 { get; set; }
        public string ConnectionFld11 { get; set; }
        public string ConnectionFld12 { get; set; }
        public int ConnectionID { get; set; }
    }
}
