//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBmysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        public Nullable<int> EquipmentModelID { get; set; }
        public Nullable<int> EquipmentCategoryID { get; set; }
        public string SerialNumber { get; set; }
        public string Region { get; set; }
        public string InventoryNumber { get; set; }
        public string EquipmentInfo { get; set; }
        public int EquipmentID { get; set; }
    }
}
