//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBmysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public file()
        {
            this.data = new HashSet<datum>();
        }
    
        public int LocationID { get; set; }
        public string FileName { get; set; }
        public string FileSN { get; set; }
        public Nullable<int> FileSize { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public Nullable<System.DateTime> FileDataDateStart { get; set; }
        public Nullable<System.DateTime> FileDataDateEnd { get; set; }
        public Nullable<System.DateTime> FileImportDate { get; set; }
        public Nullable<int> FileRecords { get; set; }
        public string FileHeader { get; set; }
        public string FileLog { get; set; }
        public int FileID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datum> data { get; set; }
        public virtual location location { get; set; }
    }
}
