//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBmysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class filter
    {
        public int LocationID { get; set; }
        public Nullable<int> EquipmentUsageID { get; set; }
        public Nullable<sbyte> FilterComparison1 { get; set; }
        public Nullable<float> FilterValue1 { get; set; }
        public Nullable<sbyte> FilterOperator { get; set; }
        public Nullable<sbyte> FilterComparison2 { get; set; }
        public Nullable<float> FilterValue2 { get; set; }
        public Nullable<System.DateTime> FilterDateFrom { get; set; }
        public Nullable<System.DateTime> FilterDateTo { get; set; }
        public int FilterID { get; set; }
    }
}
