//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBmysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public location()
        {
            this.alarms = new HashSet<alarm>();
            this.data = new HashSet<datum>();
            this.files = new HashSet<file>();
            this.userslocations = new HashSet<userslocation>();
        }
    
        public string Region { get; set; }
        public string LocationName { get; set; }
        public string LocationAddress { get; set; }
        public string LocationLongitude { get; set; }
        public string LocationLatitude { get; set; }
        public string LocationPhone { get; set; }
        public string LocationDataPhone { get; set; }
        public string LocationSiteName { get; set; }
        public Nullable<int> LocationUsageID { get; set; }
        public Nullable<int> LocationStatusID { get; set; }
        public Nullable<int> LocationComStatusID { get; set; }
        public Nullable<System.DateTime> LocationStatusDate { get; set; }
        public Nullable<int> LocationFlagID { get; set; }
        public Nullable<System.DateTime> LocationFlagDate { get; set; }
        public string LocationPath { get; set; }
        public string LocationInfo { get; set; }
        public string Graphic { get; set; }
        public Nullable<int> ImageID { get; set; }
        public string LocationChannels { get; set; }
        public int LocationID { get; set; }
        public string LocationSN { get; set; }
        public string DeviceSN { get; set; }
        public Nullable<int> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alarm> alarms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datum> data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userslocation> userslocations { get; set; }
    }
}
