//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBmysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class locationequipment
    {
        public Nullable<int> EquipmentUsageID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<int> ImageID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> LocationEquipDateAdded { get; set; }
        public Nullable<System.DateTime> LocationEquipDateRemoved { get; set; }
        public int LocationEquipID { get; set; }
    }
}
