//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBmysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int RecipID { get; set; }
        public int AlarmID { get; set; }
        public int MessageEmailStatus { get; set; }
        public int MessageSMSStatus { get; set; }
        public System.DateTime MessageDateTime { get; set; }
        public Nullable<System.DateTime> MessageDateTimeRetry { get; set; }
        public string MessageLog { get; set; }
        public int MessageID { get; set; }
    
        public virtual recip recip { get; set; }
    }
}
