//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBmysql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gserverEntities : DbContext
    {
        public gserverEntities()
            : base("name=gserverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adaptor> adaptors { get; set; }
        public virtual DbSet<alarm> alarms { get; set; }
        public virtual DbSet<app> apps { get; set; }
        public virtual DbSet<auxtable> auxtables { get; set; }
        public virtual DbSet<bussensor> bussensors { get; set; }
        public virtual DbSet<connection> connections { get; set; }
        public virtual DbSet<datum> data { get; set; }
        public virtual DbSet<dbversion> dbversions { get; set; }
        public virtual DbSet<device> devices { get; set; }
        public virtual DbSet<deviceslocation> deviceslocations { get; set; }
        public virtual DbSet<equipment> equipments { get; set; }
        public virtual DbSet<equipmentusage> equipmentusages { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<filter> filters { get; set; }
        public virtual DbSet<locationequipment> locationequipments { get; set; }
        public virtual DbSet<locationflag> locationflags { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<locationstatus> locationstatuses { get; set; }
        public virtual DbSet<measbussensor> measbussensors { get; set; }
        public virtual DbSet<meassensor> meassensors { get; set; }
        public virtual DbSet<measunit> measunits { get; set; }
        public virtual DbSet<measurement> measurements { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<recip> recips { get; set; }
        public virtual DbSet<sensadaptor> sensadaptors { get; set; }
        public virtual DbSet<sensor> sensors { get; set; }
        public virtual DbSet<site> sites { get; set; }
        public virtual DbSet<unit> units { get; set; }
        public virtual DbSet<update> updates { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userslocation> userslocations { get; set; }
    }
}
