//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBmysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class recip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recip()
        {
            this.messages = new HashSet<message>();
        }
    
        public string RecipName { get; set; }
        public Nullable<System.DateTime> RecipDateTime { get; set; }
        public string RecipEmail { get; set; }
        public string RecipSMS { get; set; }
        public Nullable<int> RecipStatus { get; set; }
        public string RecipLog { get; set; }
        public int RecipID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message> messages { get; set; }
    }
}
