//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBmysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class update
    {
        public string DeviceSN { get; set; }
        public string UpdateName { get; set; }
        public Nullable<sbyte> UpdateType { get; set; }
        public Nullable<sbyte> UpdateStatus { get; set; }
        public Nullable<System.DateTime> UpdateCreationDate { get; set; }
        public Nullable<System.DateTime> UpdateStatusDate { get; set; }
        public string UpdateInfo { get; set; }
        public string UpdateField1 { get; set; }
        public string UpdateField2 { get; set; }
        public int UpdateID { get; set; }
    }
}
