//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBmysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.devices = new HashSet<device>();
            this.locations = new HashSet<location>();
            this.userslocations = new HashSet<userslocation>();
        }
    
        public string UserName { get; set; }
        public string UserAddress { get; set; }
        public string UserCountry { get; set; }
        public string UserTel { get; set; }
        public string UserEmail { get; set; }
        public Nullable<System.DateTime> UserCreationDate { get; set; }
        public string UserField1 { get; set; }
        public string UserField2 { get; set; }
        public Nullable<int> UserField3 { get; set; }
        public Nullable<int> UserField4 { get; set; }
        public string UserInfo { get; set; }
        public Nullable<sbyte> UserAttr { get; set; }
        public int UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<device> devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<location> locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userslocation> userslocations { get; set; }
    }
}
