//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBmysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class userslocation
    {
        public long UserLocationId { get; set; }
        public int UserID { get; set; }
        public int LocationID { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual location location { get; set; }
        public virtual user user { get; set; }
    }
}
